-- Logradouro
insert into
	impressonhos.logradouro 
values 
	(null, null, Aeroporto),
	(null, null, Alameda),
	(null, null, Área),
	(null, null, Avenida),
	(null, null, Campo),
	(null, null, Chácara),
	(null, null, Colônia),
	(null, null, Condomínio),
	(null, null, Conjunto),
	(null, null, Distrito),
	(null, null, Esplanada),
	(null, null, Estação),
	(null, null, Estrada),
	(null, null, Favela),
	(null, null, Fazenda),
	(null, null, Feira),
	(null, null, Jardim),
	(null, null, Ladeira),
	(null, null, Lago),
	(null, null, Lagoa),
	(null, null, Largo),
	(null, null, Loteamento),
	(null, null, Morro),
	(null, null, Núcleo),
	(null, null, Parque),
	(null, null, Passarela),
	(null, null, Pátio),
	(null, null, Praça),
	(null, null, Quadra),
	(null, null, Recanto),
	(null, null, Residencial),
	(null, null, Rodovia),
	(null, null, Rua),
	(null, null, Setor),
	(null, null, Sítio),
	(null, null, Travessa),
	(null, null, Trecho),
	(null, null, Trevo),
	(null, null, Vale),
	(null, null, Vereda),
	(null, null, Via),
	(null, null, Viaduto),
	(null, null, Viela),
	(null, null, Vila);

-- user  
insert into scrum.user values (1, 'adm', 'Riccardo Felipe Taddei Mascarenhas', 'password', 'MASTER');